[project]
name = "isb-lib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MSMRo", email = "moises.meza@upch.pe" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
isb-lib = "isb_lib:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
