[project]
name = "isb-lib"
version = "0.1.0"
description = "Librería para el análisis simbólico y gráfico de señales y sistemas en Python (Diagramas de Polos, Ceros y respuesta temporal)"
readme = "README.md"
authors = [
    { name = "MSMRo", email = "moises.meza@upch.pe" }
]
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.5.0",
    "numpy>=1.20.0",
    "sympy>=1.8.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
